### ISSUE TITLE
get_version_v3() got an unexpected keyword argument 'credentials'

### ISSUE THREAD

**Issue by MRichards99** [tristanlt/jupyter-libcloudspawner#2] opened 2019-07-31 14:20 UTC
Hi, I'm investigating using libcloudspawner as a way of making use of an OpenStack cloud infrastructure I have access to. I installed libcloudspawner through Pip and when I select an image through the drop downs, I get the following error message:

```
[E 2019-07-31 13:56:04.999 JupyterHub user:477] Unhandled error starting xfu59478's server: {"error": {"message": "get_version_v3() got an unexpected keyword argument 'credentials'", "code": 400, "title": "Bad Request"}}
[E 2019-07-31 13:56:05.073 JupyterHub pages:148] Failed to spawn single-user server with form
    Traceback (most recent call last):
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/handlers/pages.py", line 146, in post
        await self.spawn_single_user(user, options=options)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/handlers/base.py", line 715, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
        await spawn_future
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloudspawner/spawner.py", line 236, in start
        self.user_options_from_form)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloudspawner/manager/nodemanager.py", line 251, in create_machine
        node_conf['image'] = self._get_image(imagename)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloudspawner/manager/nodemanager.py", line 90, in _get_image
        images = self.driver.list_images()
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/compute/drivers/openstack.py", line 364, in list_images
        self.connection.request('/images/detail').object, ex_only_active)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/openstack.py", line 224, in request
        raw=raw)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/base.py", line 534, in request
        action = self.morph_action_hook(action)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/openstack.py", line 291, in morph_action_hook
        self._populate_hosts_and_request_paths()
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/openstack.py", line 325, in _populate_hosts_and_request_paths
        osa = osa.authenticate(**kwargs)  # may throw InvalidCreds
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/openstack_identity.py", line 808, in authenticate
        method='POST')
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/base.py", line 636, in request
        response = responseCls(**kwargs)
      File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/libcloud/common/base.py", line 153, in __init__
        headers=self.headers)
    libcloud.common.exceptions.BaseHTTPError: {"error": {"message": "get_version_v3() got an unexpected keyword argument 'credentials'", "code": 400, "title": "Bad Request"}}
```

Here is the relevant section of my jupyterhub_config.py:

```
c.JupyterHub.spawner_class = 'libcloudspawner.spawner.LibcloudSpawner'

c.LibcloudSpawner.cloud_url = "https://mydomainname.com:4565/v3"
c.LibcloudSpawner.cloud_user = "myuser"
c.LibcloudSpawner.cloud_userpassword = "mypassword"
c.LibcloudSpawner.cloud_project = "myproject"
c.LibcloudSpawner.libcloudparams = {"arg_user_id": "myuser",
                                    "arg_key": "secret",
                                    "ex_force_auth_url": "https://openstack.stfc.ac.uk:5000/v3",
                                    "ex_tenant_name": "myproject",
                                    "ex_domain_name": "default"
                                   }

c.LibcloudSpawner.machine_sizes = [("1 CPU, 1GB RAM", "m1.tiny"),
                                   ("2 CPUs, 4GB RAM", "c3.small")]
c.LibcloudSpawner.machine_images = [("Centos-7", "Centos-7"),
                                    ("SL7 GUI", "ScientificLinux-7-Gui")]

```

As you can see, there are a few parameters that I haven't set as I'm not sure what they should be set to. 
Have you had anyone else have experiences or any suggestions on how I can move forwards?
Thanks very much!

Version according to Pip is 1.2.1.dev2

**Comment by tristanlt** [comment] 2019-08-14 07:17
Dear @MRichards99 
thank for your interest about libcloudspawner.

I have successfully reproduced your error. Since libcloud library use Keystonev2 authentication as default, we must set auth_version to force v3 :
```
c.LibcloudSpawner.libcloudparams['ex_force_auth_version'] = "3.x_password"
```

Regards,
Tristan

**Comment by tristanlt** [comment] 2019-08-14 07:20
> 
> ```
> c.JupyterHub.spawner_class = 'libcloudspawner.spawner.LibcloudSpawner'
> 
> c.LibcloudSpawner.cloud_url = "https://mydomainname.com:4565/v3"
> c.LibcloudSpawner.cloud_user = "myuser"
> c.LibcloudSpawner.cloud_userpassword = "mypassword"
> c.LibcloudSpawner.cloud_project = "myproject"
> c.LibcloudSpawner.libcloudparams = {"arg_user_id": "myuser",
>                                     "arg_key": "secret",
>                                     "ex_force_auth_url": "https://openstack.stfc.ac.uk:5000/v3",
>                                     "ex_tenant_name": "myproject",
>                                     "ex_domain_name": "default"
>                                    }
> 
> c.LibcloudSpawner.machine_sizes = [("1 CPU, 1GB RAM", "m1.tiny"),
>                                    ("2 CPUs, 4GB RAM", "c3.small")]
> c.LibcloudSpawner.machine_images = [("Centos-7", "Centos-7"),
>                                     ("SL7 GUI", "ScientificLinux-7-Gui")]
> ```

Should be :
```
c.JupyterHub.spawner_class = 'libcloudspawner.spawner.LibcloudSpawner'

c.LibcloudSpawner.cloud_url = "https://mydomainname.com:4565/v3"
c.LibcloudSpawner.cloud_user = "myuser"
c.LibcloudSpawner.cloud_userpassword = "mypassword"
c.LibcloudSpawner.cloud_project = "myproject"
c.LibcloudSpawner.libcloudparams = {"arg_user_id": "myuser",
                                    "arg_key": "secret",
                                    "ex_force_auth_version": "3.x_password",
                                    "ex_force_auth_url": "https://openstack.stfc.ac.uk:5000/v3",
                                    "ex_tenant_name": "myproject",
                                    "ex_domain_name": "default"
                                   }

c.LibcloudSpawner.machine_sizes = [("1 CPU, 1GB RAM", "m1.tiny"),
                                   ("2 CPUs, 4GB RAM", "c3.small")]
c.LibcloudSpawner.machine_images = [("Centos-7", "Centos-7"),
                                    ("SL7 GUI", "ScientificLinux-7-Gui")]
```

**Comment by MRichards99** [comment] 2019-08-14 09:12
Hi Tristan, 
Thanks for the response!
After trying your idea and making a slight change to the cloud_url in my config, I've made some progress (and resolved the initial error!), however I have encountered another error:

`libcloud.common.types.InvalidCredsError: 'Invalid credentials with the provider'`

Everything looks correct in my config, username and password are definitely correct (I've tried a second user which also gives the same error). The only thing I'm a little unsure about is the `arg_key` in the `libcloudparams`. Could you explain what this does and any other example values it could have?

**Comment by tristanlt** [comment] 2019-08-14 09:28
`arg_key` should be your password ( same as `c.LibcloudSpawner.cloud_userpassword` )

I needs to review authentication configuration since `cloud_user`, `cloud_userpassword` aren't used.

**Comment by MRichards99** [comment] 2019-08-14 09:51
Ah yes, that works just as you said. As with anything, it just leads to more errors! Spawning a server times out, I think this could be down to the keypair/SSH? I have specified a valid keypair in `ex_keyname` and I can see this works - when a VM is created, I can see OpenStack uses that keypair. Do I need to specify the private key somewhere in this config - how can Jupyterhub connect to the VM and create a notebook server if it can't SSH in (because I haven't specified the private SSH key anywhere)?

**Comment by tristanlt** [comment] 2019-08-14 11:24
Right
JupyterHub doesn't connect to instance to launch notebook.

Spawner inject one userdata script at instance creation step.

Default cloudinit script is : libcloudspawner/data/userdata.sh.j2. This script will :

1. Get JupyterHub env variables and store them inside instance /etc/default/jupyter
2. Find jupyterhub-singleuser binary inside instance ( JupyterHub must be already installed )
3. Create an unit inside systemd which launch singleuser ( as user connected on JupyterHub )
4. Activate and launch

**Comment by tristanlt** [comment] 2019-08-14 11:29
Please check 

- [x] Did instance template have JupyterHub installed ?
- [x] Is instance know one user with the same login than user connected on JupyterHub ?
- [x] Did instance OS support systemd and cloudinit ?

**Comment by tristanlt** [comment] 2019-08-14 12:07
It seems that root problem is solved, so I will close this issue. 

We can continue on Gitter for usage assistance : https://gitter.im/jupyter-libcloudspawner/community
(I'm happy to help you, this will lead to documentation enhancement )

Feel free to re-open ticket if you prefer GH issue tracker.

**Closed as completed by tristanlt** 2019-08-14 12:07 UTC
Labels: doc_enhancement
